google/GTMAppAuth

- Source/GTMTVAuthorizationResponse.m
Fixing a `Conflicting nullability specifier on return types` error for Xcode 8.3+.
Ran across this when compiling https://github.com/google/google-api-objectivec-client-for-rest
> Fix nullability error for Xcode 8.3.

- GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization.h
Strangely, the order of the `__has_include` checks matters.
I confirmed that this succeeds `pod lib lint` with and without the `--use-libraries` option and SPM still builds.
> Fix pod lib lint

- GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuth.h
This is required for Xcode 12.5 and Swift Package Manager. Verified locally that this fix resolves the issue.
> Add GTMKeychain.h to umbrella header

- GTMAppAuth/Sources/GTMAppAuthFetcherAuthorization.m
GTMSessionFetcher was updated to remove macros to bridge to the long-deprecated GTMHTTPFetcher.
> Replace reference to removed GTMBridgeAssertValidSelector

- README.md
Update link to IETF OAuth 2.0 for Native Apps reference to RFC 8252 instead of previous draft.
> Update link to OAuth 2.0 for Native Apps

- GTMAppAuth/Sources/macOS/GTMKeychain_macOS.m
Fix the error errSecDuplicateItem. Now adding password for the existing account the old one would be overwritten.
> Handle errSecDuplicateItem in savePassword on macOS

- GTMAppAuth/Sources/GTMAppAuthFetcherAuthorization+Keychain.m
- GTMAppAuth/Sources/GTMKeychain.m
- GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization+Keychain.h
- GTMAppAuth/Sources/Public/GTMAppAuth/GTMKeychain.h
- README.md
Give developers the option to use the [data protection keychain](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain?language=objc) on macOS 10.15+.  When enabled, iOS-style Keychain storage will be used instead of the default file-based storage.  Using the data protection keychain on macOS will require that the app is signed in order for Keychain operations to succeed.
> Allow developers to use the data protection keychain on macOS

- .github/workflows/tests.yml
- GTMAppAuthSwift/Sources/GTMKeychain.swift
- GTMAppAuthSwift/Tests/GTMKeychainTests.swift
- Package.swift
This change establishes support for translating this library into Swift. It adds a Swift library to the package's list of products, an associated Swift target, and a Swift test target.
> Add Swift library, target, and test target

- GTMAppAuthSwift/Sources/GTMKeychain.swift
- GTMAppAuthSwift/Tests/GTMKeychainTests.swift
- Package.swift
This change rewrites `GTMKeychain` to be written in Swift. Notable changes include:
* `GTMKeychain` now has `internal` visibility
* `GTMKeychain` has an initializer that takes in a helper type conforming to a protocol: `KeychainHelper`
* The `KeychainHelper` protocol defines the API for interacting with the Keychain
* This protocol also facilitates testing `GTMKeychain`'s behavior
> Update GTMKeychain to be written in Swift

- GTMAppAuthSwift/Sources/GTMAppAuthFetcherAuthorization.swift
- GTMAppAuthSwift/Sources/GTMKeychain.swift
- GTMAppAuthSwift/Sources/GTMOAuth2KeychainCompatibility.swift
This PR specifies better `@objc` method names in the swift-translation branch as needed. It will be used in the [examples in this branch](https://github.com/google/GTMAppAuth/tree/mdmathias/update-example/Examples).
> Update objc method names in Swift to be more friendly

- Examples/Example-iOS/Example-iOS.xcodeproj/project.pbxproj
- Examples/Example-iOS/Podfile
- Examples/Example-iOS/Source/GTMAppAuthExampleViewController.m
- Examples/Example-macOS/Example-macOS.xcodeproj/project.pbxproj
- Examples/Example-macOS/Podfile
- Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m
- GTMAppAuth/Sources/GTMAppAuthFetcherAuthorization.m
- GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization.h
Building on #155 to accommodate GTMSessionFetcher 2.1 without generating warnings stemming from the [deprecation of `GTMFetcherAuthorizationProtocol`](https://github.com/google/gtm-session-fetcher/pull/315).
> Ignore warnings from GTMFetcherAuthorizationProtocol deprecation

- .github/workflows/builds.yml
This PR adds a workflow that will attempt to archive GTMAppAuth nightly for each of the supported platforms: iOS, macOS, tvOS, and watchOS.
> Add build workflow validating archives across platforms

- .github/workflows/tests.yml
The `macOS-latest` runner alias has changed from `macOS-11` to `macOS-12`.  Under the `macOS-12` runner the watchOS build for `pod lib lint` is failing for reasons that are unclear.  Temporarily revert to running on `macOS-11` until we diagnose.
> Run tests on `macOS-11`

- .github/workflows/builds.yml
- .github/workflows/tests.yml
This change addresses the below warning that is produced from running our workflows.
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```
> Update actions to v3

- GTMAppAuth.podspec
- Package.swift
In order to allow compatibility with GTMSessionFetcher 3+ we will increase our iOS min version from 9 to 10.
> Update iOS min version to provide GTMSessionFetcher 3 compatibility

- Examples/Example-iOS/Podfile
- Examples/Example-iOS/Source/GTMAppAuthExampleViewController.m
- GTMAppAuthSwift/Sources/GTMAppAuthFetcherAuthorization.swift
Using this explicit name forces the fully qualified Swift name for this type to match the Objective-C name.
> Update GTMAppAuthFetcherAuthorization.swift to use explicit @objc name

- Examples/Example-iOS/Source/GTMAppAuthExampleViewController.h
- Examples/Example-iOS/Source/GTMAppAuthExampleViewController.m
- Examples/Example-iOS/Source/Info.plist
- GTMAppAuthSwift/Sources/AuthState.swift
- GTMAppAuthSwift/Sources/KeychainStore.swift
- GTMAppAuthSwift/Tests/Helpers/KeychainHelperFake.swift
- GTMAppAuthSwift/Tests/ObjCIntegration/GTMAuthStateTests.m
- GTMAppAuthSwift/Tests/ObjCIntegration/GTMKeychainStoreTests.m
- GTMAppAuthSwift/Tests/ObjCIntegration/GTMOAuth2KeychainCompatibilityTests.m
- GTMAppAuthSwift/Tests/Unit/AuthStateTests.swift
- GTMAppAuthSwift/Tests/Unit/KeychainStoreTests.swift
Previous usage of GTMAppAuth would potentially lead to instances of `GTMAppAuthFetcherAuthorization` being archived. Since we have renamed this type, and also changed the API considerably, we need to migrate the name to use in unarchiving via `NSKeyedUnarchiver.setClass(_:forClassName:)` so that instances previously archived can be unarchived into the renamed instance (`GTMAuthState`).
I tested archiving and unarchiving in the example app. I also tested backwards and forwards compatibility with a local branch pinned to [tag 2.0.0](https://github.com/google/GTMAppAuth/releases/tag/2.0.0). 
First, I checked out the example from tag 2.0.0 and authenticated. I then switched branches to this branch and tried to start up the example app. I was successfully able to unarchive the instance …
> Use `NSKeyedUnarchiver.setClass(_:forClassName:)` to migrate previous archives

- GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift
- GTMAppAuth/Tests/Helpers/AuthorizationTestingHelp.swift
- GTMAppAuth/Tests/Helpers/KeychainHelperFake.swift
The [nightly build workflow was failing](https://github.com/google/GTMAppAuth/actions/runs/3764133576/jobs/6398259647) due to an `@testable import GTMAppAuth` in `AuthorizationTestingHelp.swift`. This import caused the build failure because this testing helper was not located within a testing target, and so `@testable` should not be used.
The [build workflow is now passing](https://github.com/google/GTMAppAuth/actions/runs/3767451451) with this PR's changes.
> Do not import @testable target in non-test target

- GTMAppAuth/Sources/AuthSession.swift
- GTMAppAuth/Sources/KeychainStore/KeychainStore.swift
- GTMAppAuth/Tests/Unit/KeychainStore/KeychainStoreTests.swift
This PR moves `.failedToConvertKeychainDataToAuthSession` from `AuthSession.Error` to `KeychainStore.Error`, uses it in the latter, and also renames some tests in `KeychainStoreTests` to better match method names.
> Move unused error from AuthSession to KeychainStore

- .github/workflows/tests.yml
- GTMAppAuth.podspec
- GTMAppAuth/Sources/AuthSession.swift
- GTMAppAuth/Sources/KeychainStore/GTMOAuth2Compatibility.swift
- GTMAppAuth/Tests/Helpers/OIDTokenResponseTesting.swift
- GTMAppAuth/Tests/ObjCIntegration/KeychainStore/GTMOAuth2CompatibilityTests.m
- Package.swift
https://github.com/google/gtm-session-fetcher/pull/315 deprecates `GTMFetcherAuthorizationProtocol` in favor of the newer `GTMSessionFetcherAuthorizer`. The protocols are functionally the same, but invert the required and optional methods. This change helps Swift conformers avoid implementing a selector-based callback, which is awkward. In any case, we retain that conformance as well for convenience.
Additionally, this change allow us to no longer ignore warning while `pod lib lint`ing and require us to bump our dependency on `gtm-session-fetcher` to 2.1.0.
> Use GTMSessionFetcherAuthorizer instead of GTMFetcherAuthorizationProtocol

- GTMAppAuth/Sources/KeychainStore/KeychainStore.swift
For some reason, [DocC](https://developer.apple.com/documentation/docc) is interpreting our existing extension-based conformance as a [default implementation](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID529).
> Move AuthSessionStore conformance into class declaration

- GTMAppAuth/Sources/AuthSession.swift
- GTMAppAuth/Tests/Helpers/OIDTokenResponseTesting.swift
- GTMAppAuth/Tests/ObjCIntegration/GTMAuthSessionTests.m
Adds an enum mapping Swift's `AuthSession.Error` error cases to names that can be represented, and inspected, in ObjC. Also adds tests for these cases in the interop tests.
> Add AuthSession.ErrorCode and tests to ensure code export to ObjC

- .github/workflows/tests.yml
- GTMAppAuth.podspec
Per [this CocoaPods bug](https://github.com/CocoaPods/CocoaPods/issues/11558) it seems like there is a problem with how CocoaPods finds and runs tests on watchOS. Excluding watchOS from the linted platforms should unblock us to move forward with https://github.com/google/GTMAppAuth/pull/224.
> Do not lint and run tests against watchOS

- GTMAppAuth/Sources/AuthSession.swift
- GTMAppAuth/Sources/AuthSessionDelegate.swift
- GTMAppAuth/Tests/Helpers/AuthorizationTestingHelp.swift
- GTMAppAuth/Tests/Unit/AuthSessionTests.swift
This change adds a completion argument for handling updated errors in EMM flow (e.g., https://github.com/google/GoogleSignIn-iOS/pull/299).
> Add a method taking a completion argument for asynchronous error updates 

- Examples/Example-macOS/Example-macOS.entitlements
- Examples/Example-macOS/Example-macOS.xcodeproj/project.pbxproj
- Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m
- GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift
- GTMAppAuth/Sources/KeychainStore/KeychainHelper.swift
- GTMAppAuth/Sources/KeychainStore/KeychainStore.swift
- GTMAppAuth/Tests/Helpers/GTMAppAuthTestingHelpers.swift
- GTMAppAuth/Tests/Helpers/KeychainHelperFake.swift
- GTMAppAuth/Tests/Unit/KeychainStore/GTMOAuth2CompatibilityTests.swift
- GTMAppAuth/Tests/Unit/KeychainStore/KeychainStoreTests.swift
This PR addresses [a bug](#236) where the key attributes used to query the keychain were not being added correctly, and where therefore unused. The mistake was that the key names were assumed to match the static constants.
Fixes #236.
> Fix keychain key bug

- .github/workflows/builds.yml
This runner has been deprecated and removed (per [this failure](https://github.com/google/GTMAppAuth/actions/runs/9722670542)).
> Remove macOS-11 runner

- .github/workflows/scorecards.yml
V3 is deprecated as of November 30, 2024 https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact.
> Update upload artifact action to use v4.6.2

- GTMAppAuth/Sources/AuthSession.swift
- GTMAppAuth/Tests/ObjCIntegration/GTMAuthSessionTests.m
Our current implementation of sending a `NSMutableURLRequest` in a `DispatchQueue.main.async` gives a warning that will be an error in Swift 6:
```
Capture of 'request' with non-sendable type 'NSMutableURLRequest' in a `@Sendable` closure; this is an error in the Swift 6 language mode
```
Swift 6 suggests that sending in an object that does not conform to the Sendable protocol is unsafe when dealing with multiple threads, so this PR suggests a switch to use `URLRequest` which does conform to the Sendable protocol. 
Fixes #249
> Fix Swift 6 mode `@Sendable` closure warning.

- .github/workflows/builds.yml
macos-12 has been deprecated for a good bit, and the build workflow has been failing during this time.
> Update macos runner to macos-13

- GTMAppAuth/Sources/KeychainStore/GTMOAuth2Compatibility.swift
- GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift
- Package.swift
This PR fixing compile errors when using Swift 6. 
Tested: Example-iOS (Example-macOS.xcodeproj) compiles on iOS 26 iPhone 16 simulator with `swiftLanguageVersions: [.version("6")]` set in Package.swift. 
Closes: #258
> Support swift 6
